/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zuhlke.interview;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.zuhlke.interview.exception.EmptyRomanNumeralException;
import com.zuhlke.interview.exception.IllegalRomanNumeralException;

import org.junit.jupiter.api.BeforeEach;

class RomanNumeralTest {
    private RomanNumeral romanNumeral;

    @BeforeEach
    void beforeEach() {
        this.romanNumeral = new RomanNumeral();
    }

    @Test
    void testEmptyRomanNumeral() {
        assertThrows(EmptyRomanNumeralException.class,
                () -> romanNumeral.parseToInteger(null));
        assertThrows(EmptyRomanNumeralException.class,
                () -> romanNumeral.parseToInteger(""));
        assertThrows(EmptyRomanNumeralException.class,
                () -> romanNumeral.parseToInteger("  "));
    }

    @Test
    void testIllegalRomanNumeral() {
        assertThrows(IllegalRomanNumeralException.class,
                () -> romanNumeral.parseToInteger("Xb"));
    }

    @Test
    void testRomanNumeralByConstructor() {
        assertAll("test roman numeral by constructor",
                () -> assertEquals(1, new RomanNumeral("I").getValue()),
                () -> assertEquals(6, new RomanNumeral("VI").getValue()),
                () -> assertEquals(9, new RomanNumeral("IX").getValue()),
                () -> assertEquals(10, new RomanNumeral("X").getValue()));
    }

    @Test
    void testRomanNumeralIV() {
        assertEquals(4, romanNumeral.parseToInteger("IV"));
    }

    @Test
    void testRomanNumeralVI() {
        assertEquals(6, romanNumeral.parseToInteger("VI"));
    }

    @Test
    void testRomanNumeralIX() {
        assertEquals(9, romanNumeral.parseToInteger("IX"));
    }

    @Test
    void testRomanNumeralX() {
        assertEquals(10, romanNumeral.parseToInteger("X"));
    }

}
